### ISSUE TITLE
classification of events

### ISSUE THREAD

**Issue by jcezardasilva** [wooorm/html-event-attributes#1]
The list could have the classification of events.
example:
onload is a window event;
onsubmit is a form event;
onclick is a mouse event.

**Comment by wooorm** [comment]
Hi Julio! Feel free to create such a project.
This project is generated from two sources ([HTML 4](https://www.w3.org/TR/html4/index/attributes.html), [HTML](https://html.spec.whatwg.org/multipage/indices.html)), which don’t have a clear-cut definition of what you’re describing, so it wouldn’t work here!
